###########################
# Configuration for rubocop
# in .rubocop.yml 
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidlines for contributions.
#
# Any of these may be changed.

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/SpaceInsideBlockBraces:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Severity: warning

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/AsciiIdentifiers:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/FileName:
  Enabled: false
