source 'https://ruby.taobao.org/'

# Declare your gem's dependencies in qawechat.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.
# Use jquery as the JavaScript library
gem 'jquery-rails'
# wechat
gem 'wechat'
gem 'omniauth-wechat-oauth2'
# To use a debugger
# gem 'byebug', group: [:development, :test]

