物理: Physics
生物: Biology
数学: Math
化学: Chemistry
高一: s1
高二: s2
高三: s3

subjects:
  - [物理,physics]
  - [生物,biology]
  - [数学,math]
  - [化学,chemistry]
grades:
  - [高一,s1]
  - [高二,s2]
  - [高三,s3]

recharge_key: qwertyuiop0987654321qscf