-
  name: 必修1
  subject: physics
  grade: s1
  catalogues:
    - 运动的描述
    - 匀变速直线运动
    - 相互作用
    - 牛顿运动定律
-
  name: 必修2
  subject: physics
  grade: s1
  catalogues:
    - 机械能及其守恒定律
    - 曲线运动
    - 万有引力与航天
-
  name: 选修3-1
  subject: physics
  grade: s2
  catalogues:
    - 静电场
    - 恒定电流
    - 磁场
-
  name: 选修3-2
  subject: physics
  grade: s2
  catalogues:
    - 电磁感应
    - 交变电流
    - 传感器
-
  name: 选修3-3
  subject: physics
  grade: s2
  catalogues:
    - 分子动理论
    - 气体
    - 物态和物态变化
    - 热力学定律
-
  name: 选修3-4
  subject: physics
  grade: s2
  catalogues:
    - 机械振动
    - 机械波
    - 光
    - 电磁波
    - 相对论简介
-
  name: 选修3-5
  subject: physics
  grade: s2
  catalogues:
    - 动量守恒定律
    - 波粒二象性
    - 原子结构
    - 原子核
-
  name: 必修1
  subject: chemistry
  grade: s1
  catalogues:
    - 从实验学化学
    - 化学物质及其变化
    - 金属及其化合物
    - 非金属及其化合物
-
   name: 必修2
   subject: chemistry
   grade: s1
   catalogues:
     - 物质结构 元素周期律
     - 化学反应与能量
     - 有机化合物
     - 化学与可持续发展
-
  name: 选修1
  subject: chemistry
  grade: s2
  catalogues:
    - 关注营养平衡
    - 促进身心健康
    - 探索生活材料
    - 保护生存环境
-
  name: 选修2
  subject: chemistry
  grade: s2
  catalogues:
    - 走进化学工业
    - 化学与资源开发利用
    - 化学与材料的发展
    - 化学与技术的发展
-
  name: 选修3
  subject: chemistry
  grade: s2
  catalogues:
    - 原子结构与性质
    - 分子结构与性质
    - 晶体结构与性质
-
  name: 选修4
  subject: chemistry
  grade: s2
  catalogues:
    - 化学反应与能量
    - 化学反应速率和化学平衡
    - 水溶液中的离子平衡
    - 电化学基础
-
  name: 选修5
  subject: chemistry
  grade: s2
  catalogues:
    - 认识有机化合物
    - 烃和卤代烃
    - 烃的含氧衍生物
    - 生命中的基础有机化学物质
    - 进入合成有机高分子化合物的时代
-
  name: 选修6
  subject: chemistry
  grade: s2
  catalogues:
    - 从实验走进化学
    - 物质的获取
    - 物质的检测
    - 研究型实验
-
  name: 必修1
  subject: math
  grade: s1
  catalogues:
    - 集合
    - 基本初等函数
    - 函数的应用
-
  name: 必修2
  subject: math
  grade: s1
  catalogues:
    - 空间几何体
    - 点、直线、平面之间的位置关系
    - 直线与方程
    - 圆与方程
-
  name: 必修3
  subject: math
  grade: s1
  catalogues:
    - 算法初步
    - 统计
    - 概率
-
  name: 必修4
  subject: math
  grade: s1
  catalogues:
    - 三角函数
    - 平面向量
    - 三角恒等变换
-
  name: 必修5
  subject: math
  grade: s2
  catalogues:
    - 解三角式
    - 数列
    - 不等式
-
  name: 选修1-1
  subject: math
  grade: s2
  catalogues:
    - 常用逻辑用语
    - 圆锥曲线与方程
    - 导数及其应用
-
  name: 选修1-2
  subject: math
  grade: s2
  catalogues:
    - 统计案例
    - 推理与证明
    - 数系的扩充与复数的引入
    - 框图
-
  name: 选修2-1
  subject: math
  grade: s2
  catalogues:
    - 常用逻辑用语
    - 圆锥曲线与方程
    - 空间向量与立体几何
-
  name: 选修2-2
  subject: math
  grade: s2
  catalogues:
    - 导数及其应用
    - 推理与证明
    - 数系的扩充与复数的引入
-
  name: 选修2-3
  subject: math
  grade: s2
  catalogues:
    - 计数原理
    - 随机变量及其分布
    - 统计案例
-
  name: 必修1
  subject: biology
  grade: s1
  catalogues:
    - 走近细胞
    - 组成细胞的分子
    - 细胞的基本结构
    - 细胞的物质输入和输出
    - 细胞的能量供应和利用
    - 细胞的生命历程
-
  name: 必修2
  subject: biology
  grade: s1
  catalogues:
    - 遗传因子的发现
    - 基因和染色体的关系
    - 基因的本质
    - 基因的表达
    - 基因突变及其他变异
    - 从杂交育种到基因工程
    - 现代生物进化理论
-
  name: 必修3
  subject: biology
  grade: s2
  catalogues:
    - 人体的内环境与稳态
    - 动物和人体生命活动的调节
    - 植物的激素调节
    - 种群和群落
    - 生态系统的稳定性
    - 生态环境的保护
-
  name: 选修1
  subject: biology
  grade: s2
  catalogues:
    - 传统发酵技术的应用
    - 微生物的培养与应用
    - 植物的组织培养技术
    - 酶的研究与应用
    - DNA和蛋白质技术
    - 植物有效成分的提取
-
  name: 选修3
  subject: biology
  grade: s2
  catalogues:
    - 基因工程
    - 细胞工程
    - 胚胎工程
    - 生物技术的安全性和伦理性问题
    - 生态工程