-
  name: 必修一
  subject: physics
  grade: s1
  catalogues:
    - 运动的描述
    - 匀变速直线运动
    - 相互作用
    - 牛顿运动定律
-
  name: 必修二
  subject: physics
  grade: s1
  catalogues:
    - 机械能及其守恒定律
    - 曲线运动
    - 万有引力与航天