# 网易云信配置
production:
  AppKey: AppKey
  AppSecret: AppSecret

development:
  AppKey: 26d55c601d4fb126f61cb0b51bc90e6c
  AppSecret: 59068668dc6c

testing:
  AppKey: AppKey
  AppSecret: AppSecret

test:
  AppKey: AppKey
  AppSecret: AppSecret
