---
staging:
  :concurrency: 3
production:
  :concurrency: 2
testing:
  :concurrency: 2
:queues:
  - default
  - video_convert
  - sms
  - keep_account
  - wechat
  - live_studio
  - chat
  - email
  - notification
  - team_custom_message
