---
staging:
  :concurrency: 3
production:
  :concurrency: 2
development:
  :concurrency: 3
:queues:
  - default
  - video_convert
  - sms
  - keep_account
  - wechat
  - live_studio
  - chat
  - email
  - notification
