-
  name: 七年级上
  subject: 数学
  category: 初中
  grade: 初一
  content:
    chapters:
      - 有理数
      - 整式的加减
      - 一元一次方程
      - 图形认识初步
-
  name: 七年级下
  subject: 数学
  category: 初中
  grade: 初二
  content:
    chapters:
      - 相交线与平行线
      - 实数
      - 平面直角坐标系
      - 二元一次方程组
      - 不等式与不等式组
      - 数据的收集、整理与描述
-
  name: 八年级上
  subject: 数学
  category: 初中
  grade: 初二
  content:
    chapters:
      - 三角形
      - 全等三角形
      - 轴对称
      - 整式的乘法与因式分解
      - 分式
-
  name: 八年级下
  subject: 数学
  category: 初中
  grade: 初二
  content:
    chapters:
      - 二次根式
      - 勾股定理
      - 平行四边形
      - 一次函数
      - 数据的分析
-
  name: 九年级上
  subject: 数学
  category: 初中
  grade: 初三
  content:
    chapters:
      - 一元二次方程
      - 二次函数
      - 旋转
      - 圆
      - 概率初步
-
  name: 九年级下
  subject: 数学
  category: 初中
  grade: 初三
  content:
    chapters:
      - 反比例函数
      - 相似
      - 锐角三角函数
      - 投影与视图
-
  name: 八年级上
  subject: 物理
  category: 初中
  grade: 初二
  content:
    chapters:
      - 机械运动
      - 声现象
      - 物变态化
      - 光现象
      - 透镜及其应用
      - 质量与密度
-
  name: 八年级下
  subject: 物理
  category: 初中
  grade: 初二
  content:
    chapters:
      - 力
      - 运动和力
      - 压强
      - 浮力
      - 功和机械能
      - 简单机械
-
  name: 九年级
  subject: 物理
  category: 初中
  grade: 初三
  content:
    chapters:
      - 热和能
      - 内能的利用
      - 电流和电路
      - 电压 电阻
      - 欧姆定律
      - 电功率
      - 生活用电
      - 电与磁
      - 信息的传递
      - 能源与可持续发展
-
  name: 九年级上
  subject: 化学
  category: 初中
  grade: 初三
  content:
    chapters:
      - 走进化学世界
      - 我们周围的空气
      - 物质构成的奥秘
      - 自然界的水
      - 化学方程式
      - 碳和碳的氧化物
      - 燃料及其利用
-
  name: 九年级下
  subject: 化学
  category: 初中
  grade: 初三
  content:
    chapters:
      - 金属和金属材料
      - 溶液
      - 酸和碱
      - 盐 化肥
      - 化学与生活
-
  name: 七年级上
  subject: 生物
  category: 初中
  grade: 初一
  content:
    chapters:
      - 认识生物
      - 生物圈是所有生物的家
      - 观察细胞的结构
      - 细胞的生活
      - 细胞怎样产生物体
      - 没有细胞结构的微小生物病毒
      - 生物圈中有哪些绿色植物
      - 被子植物的一生
      - 绿色植物与生物圈的水循环
      - 绿色植物是生物圈中有机物的制造者
      - 绿色植物与生物圈中的碳氧平衡
      - 爱护植被，绿化祖国
-
  name: 七年级下
  subject: 生物
  category: 初中
  grade: 初一
  content:
    chapters:
      - 人的由来
      - 人体的营养
      - 人体的呼吸
      - 人体内物质的运输
      - 人体内废物的排出
      - 人体生命活动的调节
      - 人类活动对生物圈的影响
-
  name: 八年级上
  subject: 生物
  category: 初中
  grade: 初二
  content:
    chapters:
      - 各种环境中动物
      - 动物的运动和行为
      - 动物在生物圈中的作用
      - 分布广泛的细菌和真菌
      - 细菌和真菌在生物圈中的作用
      - 根据生物的特征进行分类
      - 认识生物的多样性
      - 保护生物的多样性
-
  name: 八年级下
  subject: 生物
  category: 初中
  grade: 初二
  content:
    chapters:
      - 生物的生殖和发育
      - 生物的遗传和变异
      - 生物的进化
      - 传染病和免疫
      - 用药和急救
      - 了解自己 增进健康
-
  name: 必修1
  subject: 英语
  category: 高中
  grade: 高一
  content:
    chapters:
      - Unit 1 Friendship
      - Unit 2 English around world
      - Unit 3 Travel journal
      - Unit 4 Earthquake
      - Unit 5 Nelson Mandela --- a modern hero
-
  name: 必修2
  subject: 英语
  category: 高中
  grade: 高一
  content:
    chapters:
      - Unit 1 Cultural relics
      - Unit 2 The Olympic Games
      - Unit 3 Computers
      - Unit 4 Wildlife Protection
      - Unit 5 Music
-
  name: 必修3
  subject: 英语
  category: 高中
  grade: 高一
  content:
    chapters:
      - Unit 1 Festivals around the world
      - Unit 2 Healthy eating
      - Unit 3 The Million Pound Bank Note
      - Unit 4 Astronomy:the science of the stars
      - Unit 5 Canada –"The True North"
-
  name: 必修4
  subject: 英语
  category: 高中
  grade: 高一
  content:
    chapters:
      - Unit 1 Women of achievement
      - Unit 2 Working the land
      - Unit 3 A taste of English humour
      - Unit 4 Body language
      - Unit 5 Theme parks
-
  name: 必修5
  subject: 英语
  category: 高中
  grade: 高二
  content:
    chapters:
      - Unit 1 Great scientists
      - Unit 2 The United Kingdom
      - Unit 3 Life in the future
      - Unit 4 Making the news
      - Unit 5 First Aid
-
  name: 选修6
  subject: 英语
  category: 高中
  grade: 高二
  content:
    chapters:
      - Unit 1 Art
      - Unit 2 Poems
      - Unit 3 A healthy life
      - Unit 4 Global warming
      - Unit 5 The power of nature
-
  name: 选修7
  subject: 英语
  category: 高中
  grade: 高二
  content:
    chapters:
      - Unit 1 Living well
      - Unit 2 Robots
      - Unit 3 Under the sea
      - Unit 4 Sharing
      - Unit 5 Traveling abroad
-
  name: 选修8
  subject: 英语
  category: 高中
  grade: 高二
  content:
    chapters:
      - Unit 1 A land of diversity
      - Unit 2 Cloning
      - Unit 3 Inventors and inventions
      - Unit 4 Pygmalion
      - Unit 5 Meeting your ancestors
-
  name: 总复习
  subject: 英语
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题
-
  name: 总复习
  subject: 物理
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题

-
  name: 总复习
  subject: 数学
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题

-
  name: 总复习
  subject: 化学
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题
-
  name: 总复习
  subject: 生物
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题

-
  name: 总复习
  subject: 语文
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题
-
  name: 总复习
  subject: 地理
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题

-
  name: 总复习
  subject: 政治
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题
-
  name: 总复习
  subject: 历史
  category: 高中
  grade: 高三
  content:
    chapters:
      - 第一轮复习
      - 第二轮复习
      - 第三轮复习
      - 高考专题
-
  name: 必修一
  subject: 历史
  category: 高中
  grade: 高一
  content:
    chapters:
      - 古代中国的政治制度
      - 古代希腊罗马的政治制度
      - 近代西方资本主义政治制度的确立与发展
      - 近代中国反侵略、求民主的潮流
      - 从科学社会主义理论到社会主义制度的建立
      - 现代中国的政治建设与祖国统一
      - 现代中国的对外关系
      - 当今世界政治格局的多极化趋势
-
  name: 必修二
  subject: 历史
  category: 高中
  grade: 高一
  content:
    chapters:
      - 古代中国经济的基本结构与特点
      - 资本主义世界的市场的形成和发展
      - 近代中国经济结构的变动与资本主义的曲折发展
      - 中国特色社会主义建设的道路
      - 中国近现代社会生活的变迁
      - 世界资本主义经济政策的调整
      - 苏联的社会主义建设
      - 世界经济的全球化趋势
-
  name: 必修三
  subject: 历史
  category: 高中
  grade: 高二
  content:
    chapters:
    - 中国传统文化主流思想的演变
    - 西方人文精神的起源及其发展
    - 古代中国的科学技术与文学艺术
    - 近代以来世界的科学发展历程
    - 近代中国的思想解放潮流
    - 20世纪以来中国重大思想理论成果
    - 现代中国的科技、教育与文学艺术
    - 19世纪以来的世界文学艺术

-
  name: 选修一
  subject: 历史
  category: 高中
  grade: 高二
  content:
    chapters:
    - 梭伦改革
    - 商鞅变法
    - 北魏孝文帝改革
    - 王安石变法
    - 欧洲的宗教改革
    - 默罕默德阿里改革
    - 1861年俄国农奴制改革
    - 日本明治维新
    - 戊戌变法

-
  name: 选修二
  subject: 历史
  category: 高中
  grade: 高二
  content:
    chapters:
      - 专制理论与民主思想的冲突
      - 英国议会与国王的斗争
      - 向封建专制统治宣战的檄文
      - 构建资产阶级代议制的政治框架
      - 法国民主力量与专制势力的斗争
      - 近代中国的民主思想与反对专制的斗争
      - 无产阶级和人民群众争取民主的斗争

-
  name: 选修三
  subject: 历史
  category: 高中
  grade: 高二
  content:
    chapters:
      - 第一次世界大战
      - 凡尔赛—华盛顿体系下的世界
      - 第二次世界大战
      - 雅尔塔体系下的冷战与和平
      - 烽火连绵的局部战争
      - 和平与发展

-
  name: 选修四
  subject: 历史
  category: 高中
  grade: 高二
  content:
    chapters:
      - 古代中国的政治家
      - 东西方的先哲
      - 欧美资产阶级革命时代的杰出人物
      - 亚洲觉醒的先躯
      - 无产阶级革命家
      - 杰出的科学家
-
  name: 选修五
  subject: 历史
  category: 高中
  grade: 高二
  content:
    chapters:
      - 历史和历史的“重现”
      - 人类起源之谜
      - 米诺斯宫殿遗址与克里特文明
      - 二里头文化的探索
      - 三星堆遗址──古蜀文明之谜
      - 玛雅文明的消失
      - 大津巴布韦遗址与非洲文明探秘
-
  name: 选修六
  subject: 历史
  category: 高中
  grade: 高二
  content:
    chapters:
      - 全人类共同的宝贵财富──世界文化遗产
      - 古代埃及的历史遗产
      - 古代希腊、罗马的历史遗迹
      - 欧洲文艺复兴时期的文化遗产
      - 中国著名的历史遗迹
      - 明清的宫殿、皇家园林和陵墓
      - 多姿多彩的中国古城和古村落
      - 人类非物质文化遗产──中国昆曲
      - 具有警示意义的世界文化遗产
-
  name: 必修一
  subject: 地理
  category: 高中
  grade: 高一
  content:
    chapters:
      - 行星地球
      - 地球上的大气
      - 地球上的水
      - 地表形态的塑造
      - 自然地理环境的整体性与差异性
-
  name: 必修二
  subject: 地理
  category: 高中
  grade: 高一
  content:
    chapters:
      - 人口的变化
      - 城市与城市化
      - 农业地域的形成与发展
      - 工业地域的形成与发展
      - 交通运输布局及其影响
      - 人类与地理环境的协调发展
-
  name: 必修三
  subject: 地理
  category: 高中
  grade: 高二
  content:
    chapters:
      - 地理环境与区域发展
      - 区域生态环境建设
      - 区域自然资源综合开发利用
      - 区域经济发展
      - 区际联系与区域协调发展
-
  name: 选修一
  subject: 地理
  category: 高中
  grade: 高二
  content:
    chapters:
      - 宇宙
      - 太阳系与地月系
      - 地球的演化和地表形态的变化
-
  name: 选修二
  subject: 地理
  category: 高中
  grade: 高二
  content:
    chapters:
      - 海洋概述
      - 海岸与海底地形
      - 海洋水体
      - 海－气作用
      - 海洋开发
      - 人类与海洋协调发展
-
  name: 选修三
  subject: 地理
  category: 高中
  grade: 高二
  content:
    chapters:
      - 现代旅游及其作用
      - 旅游资源
      - 旅游景观的欣赏
      - 旅游开发与保护
      - 做一个合格的现代游客

-
  name: 选修四
  subject: 地理
  category: 高中
  grade: 高二
  content:
    chapters:
      - 城乡发展与城市化
      - 城乡合理布局与协调发展
      - 城乡规划
      - 城乡建设与人居环境

-
  name: 选修五
  subject: 地理
  category: 高中
  grade: 高二
  content:
    chapters:
      - 自然灾害与人类活动
      - 中国的自然灾害
      - 防灾与减灾
-
  name: 选修六
  subject: 地理
  category: 高中
  grade: 高二
  content:
    chapters:
      - 环境与环境问题
      - 环境污染与防治
      - 自然资源的利用与保护
      - 生态环境保护
      - 环境管理及公众参与
-
  name: 选修七
  subject: 地理
  category: 高中
  grade: 高二
  content:
    chapters:
      - 数字时代与地理信息技术
      - 记录和传递地理信息的工具——地图
      - 人眼的延伸——遥感（RS）
      - 精确定位的现代工具——全球定位系统（GPS）
      - 数字时代的产物——地理信息系统（GIS）
      - 地理信息技术的集成应用与中国数字地球建设
